name: Release

on:
  workflow_run:
    workflows: ["Java CI with Gradle", "Sonar"]
    branches: [ master ]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Print current version
        run: ./gradlew cV --quiet
      - name: Create new tag
        run: ./gradlew release
      - name: Print new version
        run: ./gradlew cV --quiet